// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZGOVCYsXe5CJYW7QRbJ5OdFyaNjvSwRo',
    appId: '1:356219808071:web:28aa7733d2890660eb4462',
    messagingSenderId: '356219808071',
    projectId: 'crud-731e7',
    authDomain: 'crud-731e7.firebaseapp.com',
    storageBucket: 'crud-731e7.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAfeBp8JdEHAMW0QVaJ0r3DgeQ9kKwkm6Y',
    appId: '1:356219808071:android:0f5fd2efaa6ff4f1eb4462',
    messagingSenderId: '356219808071',
    projectId: 'crud-731e7',
    storageBucket: 'crud-731e7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJnrhLiQS3ms4euU9MJQMG5isjmTAdOAI',
    appId: '1:356219808071:ios:0a7173407296ee40eb4462',
    messagingSenderId: '356219808071',
    projectId: 'crud-731e7',
    storageBucket: 'crud-731e7.firebasestorage.app',
    iosBundleId: 'com.example.02FirestoreCrud',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCJnrhLiQS3ms4euU9MJQMG5isjmTAdOAI',
    appId: '1:356219808071:ios:0a7173407296ee40eb4462',
    messagingSenderId: '356219808071',
    projectId: 'crud-731e7',
    storageBucket: 'crud-731e7.firebasestorage.app',
    iosBundleId: 'com.example.02FirestoreCrud',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCZGOVCYsXe5CJYW7QRbJ5OdFyaNjvSwRo',
    appId: '1:356219808071:web:fe460826ce5420d6eb4462',
    messagingSenderId: '356219808071',
    projectId: 'crud-731e7',
    authDomain: 'crud-731e7.firebaseapp.com',
    storageBucket: 'crud-731e7.firebasestorage.app',
  );
}
